#!/bin/sh

if [ "$1" = "autoconf" ]; then
	if which apcaccess > /dev/null; then
		echo yes
		exit 0
	else
		echo no
		exit 0
	fi
fi

if [ "$1" = "config" ]; then
	cat <<EOF
graph_title UPS Remaining time
graph_category sensors
graph_vlabel minutes
graph_args --base 1000 -l 0
graph_info UPS Remaining estimated runtime left on battery
timeleft.label Remaining runtime
EOF
	exit 0
fi

apcaccess -u | awk '
/:/ {
	a[tolower($1)] = $3
}
END {
	print "timeleft.value", a["timeleft"]
}
'
