#!/usr/bin/bash

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
  if [ `uname -s` = SunOS ]; then
    echo no
    exit 1
  else
    echo yes
    exit 0
  fi
fi

if [ "$1" = "config" ]; then
  echo 'graph_category mail'
  echo 'graph_title Nullmailer queue'
  echo 'graph_vlabel mails'
  echo 'mails.label number'
  echo 'mails.min 0'
  exit 0
fi

echo -n "mails.value"
/usr/bin/ls -l /var/spool/nullmailer/queue/ | /opt/local/bin/grep -v total | /usr/bin/wc -l