#!/bin/sh

if [ "$1" = "autoconf" ]; then
	echo 'yes'
	exit 0
fi

if [ "$1" = "config" ]; then
	cat <<EOF
graph_title TCP Connections
graph_category network
graph_vlabel connections
graph_args --base 1000 -l 0
graph_info established tcp connections
currEstab.label connections
currEstab.draw LINE1
EOF
	exit 0
fi

kstat -p tcp:*:tcp:currEstab | sed 's/.*://g' | awk '{ print $1 ".value", $2 }'
